export enum AbilityEnum {
  Archery = 'Archery',
  Brawl = 'Brawl',
  Melee = 'Melee',
  Thrown = 'Thrown',
  War = 'War',
  Integrity = 'Integrity',
  Resistance = 'Resistance',
  Performance = 'Performance',
  Presence = 'Presence',
  Survival = 'Survival',
  Craft = 'Craft',
  Investigation = 'Investigation',
  Lore = 'Lore',
  Medicine = 'Medicine',
  Occult = 'Occult',
  Athletics = 'Athletics',
  Awareness = 'Awareness',
  Dodge = 'Dodge',
  Larceny = 'Larceny',
  Stealth = 'Stealth',
  Bureaucracy = 'Bureaucracy',
  Linguistics = 'Linguistics',
  Ride = 'Ride',
  Sail = 'Sail',
  Socialize = 'Socialize',
}
